name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost -uroot -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5 

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5 

    steps:
      - name: Github Repository 올린 파일들 불러오기
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: 서브모듈 YAML 파일 복사
        if: false
        run: |
          cp -r Onmoim-config/* src/main/resources/
          cp -r Onmoim-config/* src/test/resources/
          echo "== main/resources 목록 =="
          ls -al src/main/resources/
          echo "== test/resources 목록 =="
          ls -al src/test/resources/

      - name: JDK 21버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: 빌드 캐시 클리어
        run: ./gradlew clean --no-build-cache

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build -Dspring.profiles.active=test

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP 사용 EC2에 빌드된 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/backend-server/tobe

      - name: SSH 사용하여 EC2 접속 및 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          # EC2의 주소
          host: ${{ secrets.EC2_HOST }}
          # EC2 접속 username
          username: ${{ secrets.EC2_USERNAME }}
          # EC2의 Key 파일
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          # 실패하면 전체 실패 처리
          script_stop: true
          script: |
            # 이전 폴더 삭제
            rm -rf /home/ubuntu/backend-server/current
            
            # 폴더 다시 생성 
            mkdir /home/ubuntu/backend-server/current
            
            # tobe -> current 빌드파일 이동 
            mv /home/ubuntu/backend-server/tobe/project.jar /home/ubuntu/backend-server/current/project.jar
            
            cd /home/ubuntu/backend-server/current
            
            # 실행 중인 애플리케이션 종료 (서버가 실행 중이 아니어도 에러 없이 통과)
            sudo fuser -k -n tcp 8080 || true
            
            # 종료 대기 (3초)
            sleep 3
            
            # 애플리케이션 실행 output.log 로그 기록 
            nohup java -jar project.jar --spring.profiles.active=dev > ./output.log 2>&1 &
            
            # 폴더 삭제 
            rm -rf /home/ubuntu/backend-server/tobe
            
            # 배포 완료